ARG DOCKER_FROM=nvidia/cuda:12.3.2-devel-ubuntu22.04
FROM ${DOCKER_FROM}

# Adapted from https://gitlab.com/nvidia/container-images/cuda/-/blob/master/dist/12.2.2/ubuntu2204/devel/cudnn8/Dockerfile
ENV NV_CUDNN_VERSION 8.9.7.29
ENV NV_CUDNN_PACKAGE_NAME "libcudnn8"
ENV NV_CUDA_ADD=cuda12.2
ENV NV_CUDNN_PACKAGE "$NV_CUDNN_PACKAGE_NAME=$NV_CUDNN_VERSION-1+$NV_CUDA_ADD"
ENV NV_CUDNN_PACKAGE_DEV "$NV_CUDNN_PACKAGE_NAME-dev=$NV_CUDNN_VERSION-1+$NV_CUDA_ADD"
LABEL com.nvidia.cudnn.version="${NV_CUDNN_VERSION}"

RUN apt-get update && apt-get install -y --no-install-recommends \
    ${NV_CUDNN_PACKAGE} \
    ${NV_CUDNN_PACKAGE_DEV} \
    && apt-mark hold ${NV_CUDNN_PACKAGE_NAME} \
    && rm -rf /var/lib/apt/lists/*

##### Base

# Install system packages
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y --fix-missing\
  && apt-get install -y \
    apt-utils \
    locales \
    ca-certificates \
    && apt-get upgrade -y \
    && apt-get clean

# UTF-8
RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8
ENV LC_ALL=C

RUN apt-get install -y \
      build-essential \
      checkinstall \
      curl \
      g++ \
      gcc \
      git \
      perl \
      patchelf \
      pkg-config \
      protobuf-compiler \
      python3-dev \
      rsync \
      time \
      unzip \
      wget \
      zip \
      zlib1g \
      zlib1g-dev \
      file \
      gnupg \
      gstreamer1.0-plugins-good \
      imagemagick \
      libatk-adaptor \
      libatlas-base-dev \
      libboost-all-dev \
      libeigen3-dev \
      libfaac-dev \
      libfreetype6-dev \
      libgflags-dev \
      libglew-dev \
      libglu1-mesa \
      libglu1-mesa-dev \
      libgphoto2-dev \
      libgstreamer1.0-dev \
      libgstreamer-plugins-bad1.0-0 \
      libgstreamer-plugins-base1.0-dev \
      libhdf5-dev \
      libhdf5-serial-dev \
      libjpeg-dev \
      liblapack-dev \
      libmp3lame-dev \
      libopenblas-dev \
      libopencore-amrnb-dev \
      libopencore-amrwb-dev \
      libopenjp2-7 \
      libopenjp2-7-dev \
      libopenjp2-tools \
      libopenjpip-server \
      libpng-dev \
      libpostproc-dev \
      libprotobuf-dev \
      libtbb2 \
      libtbb-dev \
      libtheora-dev \
      libtiff5-dev \
      libv4l-dev \
      libvorbis-dev \
      libwebp-dev \
      libx264-dev \
      libx265-dev \
      libxi-dev \
      libxine2-dev \
      libxmu-dev \
      libxvidcore-dev \
      libzmq3-dev \
      v4l-utils \
      x264 \
      yasm \
      libomp-dev \
      libsox-dev \
      libsox-fmt-all \
      libsphinxbase-dev \
      sphinxbase-utils \
      libass-dev \
      libc6 \
      libc6-dev \
      libnuma1 \
      libnuma-dev \
      libopus-dev \
      libtool \
      libvpx-dev \
    && apt-get clean

CMD /bin/bash
